import type { Metadata } from 'next'

import './globals.scss'
import { play, fkalakokz } from '../fonts'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" type="image/x-icon" href="/favicon.png" />
      </head>
      <body className={[play.className, fkalakokz.variable].join(' ')}>
        {children}
      </body>
    </html>
  )
}
